### ISSUE TITLE
Prometheus Exporter

### ISSUE THREAD

**Issue by tuladhar** [soraro/kurt#32]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Expose as prometheus metrics. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hognala** [comment]
What's it worth to you @tuladhar ?

**Comment by kwsorensen** [comment]
Thanks for filing this enhancement request @tuladhar. I'd like to learn more about your use case. 

Are you looking to run kurt as a binary on a host and have Prometheus scrap the host?
OR
Are you looking to have kurt run in a container on a cluster and have it get scraped that way?

**Comment by tuladhar** [comment]
Thanks for the response. The use case I'm envisioning is the latter one. To run in a cluster and scrape it.

**Comment by aro5000** [comment]
Hey @tuladhar thanks for filling out the request! I want to understand the use-case better. I would think that if you're running a prometheus stack you'd probably just want to use something like [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics), specifically [pod-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) for `kube_pod_container_status_restarts_total`. We built this tool for quick ad-hoc troubleshooting purposes without really thinking anyone would want to use it for long-term metrics. Is there something you think kurt could do better or differently than kube-state-metrics?
