### ISSUE TITLE
doesn't work with multiple kubeconfig files

### ISSUE THREAD

**Issue by ahmetb** [soraro/kurt#35]
v0.2.1 returns this error:

```
panic: stat /Users/ahmet/.kube/config:/Users/ahmet/.kube/twconfig: no such file or directory
```

if I set a `KUBECONFIG=file1:file2:...` format.

**Comment by aro5000** [comment]
Thanks for this @ahmetb! I actually didn't realize this was a `KUBECONFIG` convention, but I am able to reproduce it by spinning up a couple of minikube clusters locally. Going to take a look to see what the most idiomatic way to address this is :slightly_smiling_face:

**Comment by ahmetb** [comment]
I recommend sticking to client-go library and methods it offers.

**Comment by aro5000** [comment]
@ahmetb I opened a PR for this under the branch `35-support-multiple-kubeconfigs`. Would you be willing to build from that and see if this addresses your use-case? It seems to work for me testing with multiple minikube clusters locally. 

Also, given all your work in this space, I'd be interested if there's a better / more idiomatic approach to solving this, but following the client-go docs, using `clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)` seemed pretty much "built-in" to the library. I was pleasantly surprised!

Thanks again for raising this!

**Comment by kwsorensen** [comment]
Thanks for filing this @ahmetb. We were able to get a fix, cut a release and get our updated version into Krew (https://github.com/kubernetes-sigs/krew-index/pull/2070) 

Let us know if you find any other issues!
