### ISSUE TITLE
Fix wording on PR template

### ISSUE THREAD

**Issue by aro5000** [soraro/kurt#7]
The wording on this line does not make it clear what the expectation is: https://github.com/soraro/kurt/blob/f3b3a8976b26be2f365db6490ff5453d07e9670f/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L4

Maybe something like:
>Discussion of the issue should be done on the issue. PR's should only be related to code review.

Probably don't need it at this time, but at some point we could look at making a `CONTRIBUTING.md` file ([example](https://github.com/helm/helm/blob/main/CONTRIBUTING.md)).

**Comment by kwsorensen** [comment]
@aro5000 agree this isn't clear... What are your thoughts on the following?

2. Clarification on feature functionality should be done on the [Issues page](https://github.com/soraro/kurt/issues) and implementation details should be done on the [Pull Request](https://github.com/soraro/kurt/pulls).
